application: connex-apt
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /index
  script: guestbook.application  

- url: /create
  script: create.application

- url: /view
  script: view.application

- url: /search
  script: search.application

- url: /trending
  script: trending.application

- url: /social
  script: social.application      

- url: /.*
  script: guestbook.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest